#!/usr/bin/env python3
"""Tier-1 assembly engine. Spec is the SOURCE; this generates the artifact.
Pipeline: load spec -> compile landings -> gate-check -> REFUSE or emit HTML.
Because the checked surface is compiled from the same spec the HTML is rendered
from, spec and artifact cannot drift (the Tier-0 hand-extraction risk is gone)."""
import json, sys, html as H
import gate_check

def reachable(spec):
    def counts(n):
        d={0:1}
        for _ in range(n):
            nd={}
            for s,c in d.items():
                for f in range(1,6): nd[s+f]=nd.get(s+f,0)+c
            d=nd
        return d
    sN,tN=spec["axes"]["self"]["items"],spec["axes"]["team"]["items"]
    thr=spec["scoring"]["quadrant"]["threshold"]; B=spec["scoring"]["bands"]; out=set()
    for ss in counts(sN):
        for ts in counts(tN):
            s,t=ss/sN,ts/tN; sH,tH=s>=thr,t>=thr
            q='aligned' if(sH and tH)else 'lone' if(sH and not tH)else 'martyr' if(not sH and tH)else 'grinder'
            m=(s+t)/2; g=abs(s-t); c=B[q]
            band=(c["high"] if m>=c["cut"] else c["low"]) if c["measure"]=="mean" else (c["high"] if g>=c["cut"] else c["low"])
            out.add(f"{q}|{band}")
    return out

def compile_landings(spec):
    """Compose every reachable address into a landing. text includes ALL opener
    variants, so the voice/evidence lint covers every phrasing a user could see."""
    qd=spec["content"]["quadrants"]; dl=spec["content"]["depthLeads"]; land={}
    for addr in reachable(spec):
        q=addr.split("|")[0]; c=qd[q]
        text=" ".join(c["opener"]) + " " + dl[addr] + " " + " ".join(c["body"])
        land[addr]={"gap_family":c["gap_family"],"validate_first":c["validate_first"],
                    "licensed_inputs":["self","team"],"text":text}
    return land

def emit_html(spec):
    data=json.dumps({"meta":spec["meta"],"questions":spec["questions"],"axes":spec["axes"],
        "scoring":spec["scoring"],"content":spec["content"]}, ensure_ascii=False)
    # generic, spec-agnostic engine JS (same for any spec); variant pick by session hash
    return f"""<!DOCTYPE html>
<!-- GENERATED by engine.py from spec-tier1.json. Do not hand-edit: edit the
     spec and recompile. Emission is gate-checked; a blocking failure aborts. -->
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{H.escape(spec['meta']['title'])}</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f4f1ea;color:#1a1a1a;line-height:1.5;min-height:100vh;padding:40px 20px}}
.container{{max-width:720px;margin:0 auto}}
.card{{background:#fff;padding:48px;border-radius:4px;box-shadow:0 2px 12px rgba(0,0,0,.04)}}
h1{{font-size:34px;font-weight:600;margin-bottom:18px;letter-spacing:-.02em}}
p{{font-size:17px;color:#444;margin-bottom:14px}}
.counter{{font-size:13px;color:#888;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px}}
.stem{{font-size:22px;font-weight:500;margin:6px 0 26px}}
.opt{{display:block;width:100%;text-align:left;background:#fafaf7;border:1px solid #e8e4dc;padding:15px 18px;border-radius:4px;margin-bottom:9px;cursor:pointer;font-size:16px;font-family:inherit;line-height:1.45}}
.opt:hover{{border-color:#2c5f5d;background:#f0ede5}}
.opt.sel{{background:#e8f0ef;border-color:#2c5f5d}}
.nav{{display:flex;justify-content:space-between;margin-top:28px}}
button.primary{{background:#2c5f5d;color:#fff;border:none;padding:13px 30px;border-radius:4px;font-size:15px;cursor:pointer;font-family:inherit}}
button.primary:disabled{{background:#b8c5c4}}
button.sec{{background:none;border:none;color:#666;font-size:15px;cursor:pointer;font-family:inherit}}
.qname{{font-size:34px;font-weight:600;margin-bottom:8px}}
.lead{{color:#2c5f5d;font-weight:500;font-size:17px;margin:14px 0}}
.rep p{{font-size:16px;color:#333;line-height:1.65;margin-bottom:16px}}
.rep p.op{{font-size:18px;color:#1a1a1a;font-weight:500}}
.prog{{display:flex;gap:4px;margin-bottom:30px}}.pd{{flex:1;height:3px;background:#e8e4dc;border-radius:2px}}.pd.on{{background:#2c5f5d}}
.mxwrap{{max-width:420px;margin:24px auto 6px}}
.matrix{{position:relative;width:100%;aspect-ratio:1;background:#fafaf7;border:1px solid #e8e4dc}}
.cell{{position:absolute;width:50%;height:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:10px;text-align:center;border:1px solid #e8e4dc}}
.cell.tl{{top:0;left:0}}.cell.tr{{top:0;right:0}}.cell.bl{{bottom:0;left:0}}.cell.br{{bottom:0;right:0}}
.cell .cn{{font-size:13px;font-weight:600;color:#9a958c;line-height:1.2}}
.cell .cs{{font-size:10px;color:#bcb6aa;margin-top:4px;line-height:1.2;text-transform:uppercase;letter-spacing:.03em}}
.cell.active{{background:#eef4f3;border-color:#2c5f5d}}
.cell.active .cn{{color:#2c5f5d}}
.mk{{position:absolute;width:20px;height:20px;background:#2c5f5d;border:3px solid #fff;border-radius:50%;box-shadow:0 0 0 2px #2c5f5d,0 3px 10px rgba(44,95,93,.35);transform:translate(-50%,-50%);z-index:5}}
.axx{{text-align:center;font-size:12px;color:#777;margin-top:10px;letter-spacing:.03em}}
.axy{{text-align:center;font-size:12px;color:#777;margin-top:2px;letter-spacing:.03em}}
.youare{{text-align:center;font-size:13px;color:#2c5f5d;font-weight:500;margin:6px 0 0}}
.lc{{max-width:480px;margin:26px auto 4px}}
.lcbar{{display:flex;gap:5px}}
.lcseg{{flex:1;text-align:center;padding:9px 4px;border:1px solid #e8e4dc;border-radius:4px;font-size:12px;color:#9a958c;background:#fafaf7;position:relative}}
.lcseg.done{{color:#6f928f;background:#f1f5f4}}
.lcseg.here{{background:#e8f0ef;border-color:#2c5f5d;color:#2c5f5d;font-weight:600}}
.lcseg .cmt{{position:absolute;top:-17px;left:0;right:0;font-size:9px;color:#b06a2c;font-weight:600;letter-spacing:.02em}}
.lccap{{text-align:center;font-size:11px;color:#999;margin-top:18px}}
.norm{{background:#f7f1e7;border-left:3px solid #c9912f;padding:14px 16px;border-radius:4px;margin:16px 0 0;font-size:15px;color:#574a32;line-height:1.6}}
</style></head><body><div class="container">
<div id="intro" class="card"></div>
<div id="quiz" class="card" style="display:none"><div class="prog" id="prog"></div><div class="counter" id="ct"></div><div class="stem" id="stem"></div><div id="opts"></div><div class="nav"><button class="sec" id="back" onclick="back()">← Back</button><button class="primary" id="nx" onclick="next()" disabled>Next</button></div></div>
<div id="res" class="card" style="display:none"><div class="qname" id="qn"></div>
<div class="mxwrap"><div class="matrix" id="mx">
<div class="cell tl" id="c_lone"><div class="cn"></div><div class="cs"></div></div>
<div class="cell tr" id="c_aligned"><div class="cn"></div><div class="cs"></div></div>
<div class="cell bl" id="c_grinder"><div class="cn"></div><div class="cs"></div></div>
<div class="cell br" id="c_martyr"><div class="cn"></div><div class="cs"></div></div>
<div class="mk" id="mk"></div></div>
<div class="axx" id="axx"></div><div class="axy" id="axy"></div></div>
<p class="youare" id="youare"></p>
<div class="lc" id="lc" style="display:none"><div class="lcbar" id="lcbar"></div><div class="lccap" id="lccap"></div></div>
<div class="norm" id="norm" style="display:none"></div>
<div class="rep" id="rep"></div><p style="text-align:center;margin-top:30px"><button class="sec" onclick="location.reload()">Start over</button></p></div>
</div>
<script>
const SPEC = {data};
const Q = SPEC.questions, SC = SPEC.scoring;
let cur=0, ans=Array(Q.length).fill(null), order=[], seed=Math.random();
function sh(a){{for(let i=a.length-1;i>0;i--){{const j=(Math.random()*(i+1))|0;[a[i],a[j]]=[a[j],a[i]]}}return a}}
function start(){{order=Q.map(q=>sh(q.options.map((t,i)=>({{t,v:i+1}}))));document.getElementById('intro').style.display='none';document.getElementById('quiz').style.display='block';render()}}
function render(){{const q=Q[cur];document.getElementById('ct').textContent=`Question ${{cur+1}} of ${{Q.length}}`;
 document.getElementById('stem').textContent=q.stem;
 const pr=document.getElementById('prog');pr.innerHTML='';for(let i=0;i<Q.length;i++){{const d=document.createElement('div');d.className='pd'+(i<=cur?' on':'');pr.appendChild(d)}}
 const o=document.getElementById('opts');o.innerHTML='';order[cur].forEach(op=>{{const b=document.createElement('button');b.className='opt'+(ans[cur]===op.v?' sel':'');b.textContent=op.t;b.onclick=()=>{{ans[cur]=op.v;render()}};o.appendChild(b)}});
 document.getElementById('back').disabled=cur===0;document.getElementById('nx').disabled=ans[cur]===null;document.getElementById('nx').textContent=cur===Q.length-1?'See reflection':'Next'}}
function next(){{if(ans[cur]===null)return;if(cur<Q.length-1){{cur++;render();scrollTo({{top:0,behavior:'smooth'}})}}else show()}}
function back(){{if(cur>0){{cur--;render();scrollTo({{top:0,behavior:'smooth'}})}}}}
function score(){{const sm={{}},cn={{}};Q.forEach((q,i)=>{{sm[q.axis]=(sm[q.axis]||0)+ans[i];cn[q.axis]=(cn[q.axis]||0)+1}});const m={{}};for(const k in sm)m[k]=sm[k]/cn[k];return m}}
function quad(s,t){{const sH=s>=SC.quadrant.threshold,tH=t>=SC.quadrant.threshold;return sH&&tH?'aligned':sH&&!tH?'lone':!sH&&tH?'martyr':'grinder'}}
function band(s,t,q){{const c=SC.bands[q],m=(s+t)/2,g=Math.abs(s-t);return c.measure==='mean'?(m>=c.cut?c.high:c.low):(g>=c.cut?c.high:c.low)}}
function pick(arr){{return arr[Math.floor(seed*arr.length)%arr.length]}}  // stable per session
function show(){{const s=score(),q=quad(s.self,s.team),b=band(s.self,s.team,q),key=q+'|'+b,c=SPEC.content.quadrants[q];
 document.getElementById('quiz').style.display='none';document.getElementById('res').style.display='block';
 document.getElementById('qn').textContent=c.name;
 // label the four cells from the spec, in axis terms
 const AX=SPEC.axes, sL=(AX.self.label||'Self'), tL=(AX.team.label||'Team');
 const cells={{lone:[sL+' high',tL+' low'],aligned:[sL+' high',tL+' high'],grinder:[sL+' low',tL+' low'],martyr:[sL+' low',tL+' high']}};
 for(const k of Object.keys(cells)){{const el=document.getElementById('c_'+k);el.querySelector('.cn').textContent=SPEC.content.quadrants[k].name;el.querySelector('.cs').textContent=cells[k][0]+' \\u00b7 '+cells[k][1];el.classList.remove('active');}}
 document.getElementById('c_'+q).classList.add('active');
 document.getElementById('axx').textContent=tL+' (low \\u2192 high) along the bottom';
 document.getElementById('axy').textContent=sL+' (low \\u2192 high) up the side';
 const mk=document.getElementById('mk');mk.style.left=(5+((s.team-1)/4)*90)+'%';mk.style.top=(95-((s.self-1)/4)*90)+'%';
 document.getElementById('youare').textContent='You are here \\u2192 '+c.name+'  ('+sL+' '+s.self.toFixed(1)+' / '+tL+' '+s.team.toFixed(1)+')';
 // Stage 2: lifecycle bar + normative gap (only if the spec defines a lifecycle and a journey axis was answered)
 const LC=SC.lifecycle;
 if(LC && s.journey!=null){{
   const stageIdx=x=>{{let i=0;LC.cuts.forEach(cut=>{{if(x>=cut)i++}});return i}};
   const maturity=(s.self+s.team)/2, ai=stageIdx(maturity), ci=stageIdx(s.journey);
   const bar=document.getElementById('lcbar');bar.innerHTML='';
   LC.stages.forEach((nm,i)=>{{const seg=document.createElement('div');
     seg.className='lcseg'+(i<ai?' done':'')+(i===ai?' here':'');
     seg.innerHTML=((i===ci&&ci!==ai)?'<div class="cmt">committed \\u25be</div>':'')+nm;
     bar.appendChild(seg);}});
   document.getElementById('lccap').textContent='Filled = where your AI adoption actually sits today. Marked = where your commitment aims.';
   document.getElementById('lc').style.display='block';
   const diff=ci-ai, gs=diff>=(SC.normative.behind_by||1)?'behind':(diff<=-1?'ahead':'on_track');
   const qn=c.name.replace(/^[Tt]he\\s+/,'');
   let tx=(SPEC.content.normative||{{}})[gs]||'';
   tx=tx.split('{{committed}}').join(LC.stages[ci]).split('{{achieved}}').join(LC.stages[ai]).split('{{quadrant}}').join(qn);
   const ne=document.getElementById('norm');ne.textContent=tx;ne.style.display=tx?'block':'none';
 }}
 document.getElementById('rep').innerHTML=`<p class="op">${{pick(c.opener)}}</p><p class="lead">${{SPEC.content.depthLeads[key]}}</p>`+c.body.map(p=>`<p>${{p}}</p>`).join('');
 scrollTo({{top:0,behavior:'smooth'}})}}
const STEMS=Q.map(q=>q.stem||'');
const I=document.getElementById('intro');I.innerHTML=`<h1>${{SPEC.meta.title}}</h1>`+SPEC.meta.intro.map(p=>`<p>${{p}}</p>`).join('')+`<p style="margin-top:24px"><button class="primary" onclick="start()">Begin</button></p>`;
</script></body></html>"""

def main():
    args=[a for a in sys.argv[1:] if a!="--check"]
    check_only="--check" in sys.argv
    spec=json.load(open(args[0]))
    land=compile_landings(spec)
    aux=list((spec.get("content",{}).get("normative",{}) or {}).values())
    check_spec={**spec,"landings":land,"aux_texts":aux}
    R=gate_check.run(check_spec)
    blocked=[g for g,sev,st,_ in R if sev=="BLOCK" and st=="FAIL"]
    print("ENGINE gate pre-check:", "REFUSED "+str(blocked) if blocked else "OK")
    for g,sev,st,d in R:
        if sev=="BLOCK": print(f"   [{st}] {g}")
    if blocked:
        print("Emission aborted."); sys.exit(1)
    if check_only:
        print("Check-only: all blocking gates pass (no artifact written)."); sys.exit(0)
    open(args[1],"w").write(emit_html(spec))
    print("Emitted:", args[1])

if __name__=="__main__": main()
